<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net5.0;net6.0;net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<PackageProjectUrl>https://github.com/ZeeLyn/Dapper.Extensions</PackageProjectUrl>
		<PackageId>Dapper.Extensions.Caching.Redis</PackageId>
		<Description>A dapper extension library. Support MySQL,SQL Server,PostgreSQL,SQLite,Oracle and ODBC, Support cache.</Description>
		<Version>5.4.3</Version>
		<Authors>ZeeLyn</Authors>
		<PackageTags>Dapper,Dapper Extensions,DapperExtensions,Dapper.Extensions.NetCore,Extensions,DataBase,Sql Server,MSSQL,MySQL,PostgreSQL,SQLite,ODBC,Cahce,Caching,Redis,Memory,RedisCaching,MemoryCaching</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<LangVersion>latest</LangVersion>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>icon.jpg</PackageIcon>
		<RepositoryUrl>https://github.com/ZeeLyn/Dapper.Extensions</RepositoryUrl>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="PartitionRedisCacheProvider.cs" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\icon.jpg">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="FreeRedis" Version="1.5.5" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Dapper.Extensions\Dapper.Extensions.csproj" />
	</ItemGroup>

</Project>
